<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//*[@id=&quot;aspnetForm&quot;]/div[3]/div/div/div[2]/a[2]</description>
   <name>Select_Editions_Button</name>
   <tag></tag>
   <elementGuidId>0d8197ca-aeb6-4fde-a456-1b6222ef9562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;aspnetForm&quot;]/div[3]/div/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
