<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboard Your CustomersMy Feedback</name>
   <tag></tag>
   <elementGuidId>7ff7b702-3d6b-4f9f-bc88-608b1474db6a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v2-menu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dashboard Your CustomersMy FeedbackCall Back RequestsReceived a Negative ReviewGrow Your BusinessMy Profile PageProfile TextSearch AppearanceCompany LogoBanner ImagesUpload Your PLIMy PhotosManage AlbumsFeatured ItemsTeam Photo'sMy StatsAdvertise in a DirectoryExpand Your AreaContact PreferencesMarketing MaterialsScamsWelcomeYour AccountUseful DocumentsVetting InformationTrading Standards DocumentsOther Useful DocumentsUpload Your PLIPaymentsPay by CardAcceptacardMembershipOffers and DiscountsNewsMy StatsMember AchievementsPolicy &amp; T&amp;C'sWhistle Blower</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Top&quot;)/div[@class=&quot;v2-menu&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Top']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
   </webElementXpaths>
</WebElementEntity>
