<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Dittto</description>
   <name>Login_Button</name>
   <tag></tag>
   <elementGuidId>80bbc961-fbbc-48b5-843f-86d5ebaceeae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LoginButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
