<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Marketing_Report_Download_Button</name>
   <tag></tag>
   <elementGuidId>1febc3d6-f6cc-4841-a047-e957682b565c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cdk-accordion-child-3&quot;]/div/mat-panel-description/app-report-form/div/div/div[3]/div/button/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
