<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Do not send_1</name>
   <tag></tag>
   <elementGuidId>48e3e364-f332-4e27-9b06-447141ff0f30</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-field-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailDDL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do not sendOtherCompany email address: jon.wood@checkatrade.comMr Daniel Davis: daniel.davis@edaxis.co.ukMr Testing Team: support@checkatrade.comMr Testing Team: support@checkatrade.comMr Alexander Nunn: alexander.nunn@checkatrade.comMr Alexander Nunn: alexander.nunn@checkatrade.comMr Alex McCallio: alex.mccallion@hotmail.co.ukMrs Sindhura Voona: christopher.byrom@blah.comMrs Sindhura Voona: christopher.byrom@blah.comMr Rehana Shadab: rehana.shedab@checkatrade.comMr Richard Audemars: richard.audemars@checkatrade.comMr Sian Taylor: sian.taylor@checkatrade.comMr Chantel Lineham: chantel.lineham@checkatrade.comMr Neil Hibbert: neil.hibbert@checkatrade.comMiss Eleanor Jordan: eleanor.jordan@checkatrade.comMr Ivan G-S: ivan.gutowski-smith@checkatrade.comMr Ciar Baharie: ciar.baharie@checkatrade.comMr Ryan B: ryan.butt@checkatrade.comMr Michael Eason: michael.eason@checkatrade.comMr Mike Fairman: mike.fairman@checkatrade.comMrs Becky Cheshire: becky.cheshire@checkatrade.comMr Colin Wisdom: colin.wisdom@checkatrade.comMr Simon Ip: simon.ip@checkatrade.comMr Chris Almond: chris.almond@standingongiants.comMr Mark Bagnall: mark.bagnall@checkatrade.comMr Jon Wood: jon.wood@checkatrade.comMr Linda Hardy: linda.hardy@checkatrade.comMr Dan Staples: dan.staples@checkatrade.comMr Charlotte Carter: charlotte.carter@checkatrade.comMr L P: l.p@checkatrade.comMr Ketih Reed: keith.reed@checkatrade.comMr Tom Amis: tom.amis@checkatrade.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-field-1&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='form-field-1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workAlertsControls']/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send emails to:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where would you like us to send your work alerts?'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send sms to:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Specify:'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
