<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Feedback_Graphic</description>
   <name>Feedback_Graphic</name>
   <tag></tag>
   <elementGuidId>ba20799c-23e3-42c5-9a30-b65078dfd92a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ctl00_CP1_content&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
