<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>attempt_Resolution_span_No</name>
   <tag></tag>
   <elementGuidId>459b0fdc-fa0f-470d-9481-996450a5c906</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;ctl00_content_ctlYourExperienceUpdatePanel&quot;]/div[8]/div[2]/div/div/label[2]/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ctl00_content_ctlYourExperienceUpdatePanel&quot;]/div[8]/div[2]/div/div/label[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
